networks:
  default:

volumes:
  db:
    driver: local

services:
  api:
    build: ./api
    command: sh -c 'npm run docker'
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://localhost/mydb
    depends_on:
      - mongo
    networks:
      - default

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - default
