networks:
  default:

volumes:
  db:
    driver: local

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydb?schema=public
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - TZ=GMT+2
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
